#!/usr/bin/env python3
import json,re
from pathlib import Path
R=Path(__file__).resolve().parents[1]; S=R/'data/shows/backyard-rockets-s1'
def load(p): return json.loads(p.read_text(encoding='utf-8'))
def dump(p,x): p.write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
p=R/'data/shows.json'; m=load(p); sh=next(x for x in m if x.get('id')=='backyard-rockets-s1')
keep=[]; inserted=False
new=[{'file':'encoded/scenes_e04_trip_point.json.gzb64','encoding':'gzip-base64'},{'file':'encoded/scenes_e05_reserve_margin.json.gzb64','encoding':'gzip-base64'},{'file':'encoded/scenes_e06_ground_loop.json.gzb64','encoding':'gzip-base64'},{'file':'encoded/scenes_e07_ablative_armor.json.gzb64','encoding':'gzip-base64'},{'file':'encoded/scenes_e08_sky_piercer.json.gzb64','encoding':'gzip-base64'}]
for o in sh['sceneOverlays']:
 f=o['file']; late=bool(re.search(r'(?:^|/)(?:scenes_)?e0[4-8]',f))
 if late:
  if not inserted: keep+=new; inserted=True
 else: keep.append(o)
sh['sceneOverlays']=keep; dump(p,m)
p=S/'characters.json'; c=load(p)
t=('TAMSIN — COMMUNITY WATER-SYSTEMS OPERATOR. Medium build; warm brown skin; dark brown hair normally tied in a low ponytail; faded indigo work shirt; light canvas utility vest with water-system tags; tan field trousers; practical boots; clear safety glasses clipped at the collar. She is a visible community-side operator of Public Sky rather than a Launch-Shop subordinate. Her authority comes from participating communities and can be rotated away from her. Keep her visual identity grounded, maintained and distinct from Lucia and Tamz.')
c['tamsin']={'name':'Tamsin','handle':'@brk.Tamsin','text':t,'visualAnchor':'Community water-systems operator with warm brown skin, dark brown hair in a low ponytail, faded indigo work shirt, light canvas utility vest with water-system tags, tan field trousers, practical boots and clear safety glasses at the collar.','continuityLocks':['low dark-brown ponytail','faded indigo work shirt','light canvas water-systems utility vest','tan field trousers and practical boots','clear safety glasses clipped at collar','community operator, not Launch-Shop tactical crew'],'voiceProfile':'Practical, dry and civic-minded; names tradeoffs plainly, refuses false consensus and does not defer community decisions to the Launch-Shop crew.'}
c['@brk.Tamsin']={'name':'Tamsin','handle':'@brk.Tamsin','text':t}; dump(p,c)
p=S/'documentary-interstitials.json'; d=[x for x in load(p) if x.get('episode') not in {'S1E06','S1E07','S1E08'}]
d += [
{'id':'BR_S1E06_DOC_TG07','episode':'S1E06','after':'BR_S1E06_A02_SC04','channel':'tethergrid','setting':'Tetherwell network-safety film — clean basin map showing isolated wells and delayed coordination.','summary':'A precise basin diagram separates into disconnected local clusters. Individually safe pump icons turn amber when their combined draw arrives too late for the central model to reconcile.','narration':'Water can be overdrawn by individually reasonable decisions. Shared resources require shared timing, not merely good intentions.'},
{'id':'BR_S1E06_DOC_DL07','episode':'S1E06','after':'BR_S1E06_A02_SC06','channel':'dryline','setting':'The Dryline Report — community coordination desks and ridge relays operating during the orbital closure.','summary':'Paper ledgers, physical trip flags and ridge-relay status lamps are compared across three communities. One delayed update is visibly marked and corrected before the next draw period begins.','narration':'The new network is slower without orbit. It is also still rationing. During this outage, participating wells reduced combined draw instead of increasing it.'},
{'id':'BR_S1E07_DOC_TG08','episode':'S1E07','after':'BR_S1E07_A02_SC03','channel':'tethergrid','setting':'Tethergrid launch-safety advisory — controlled footage of the failed ablative burn test.','summary':'A test nose cone glows under heat as a strip of ceramic begins to peel. The frame freezes on the lifted edge while an abort marker appears beside the temperature curve.','narration':'High-energy flight punishes small material errors at extraordinary speed. Unlicensed test programs transfer that risk to everyone beneath the corridor.'},
{'id':'BR_S1E07_DOC_DL08','episode':'S1E07','after':'BR_S1E07_A02_SC04','channel':'dryline','setting':'The Dryline Report — side-by-side review of the failed burn and the complete published test record.','summary':'The same failure footage continues beside the full temperature trace, bond data and visible abort threshold. A second panel lists the interception-test data Tethergrid does not publish.','narration':'The failure is real. So is the abort. Launch-Shop published the complete test record within an hour. Tethergrid does not release comparable interception data.'},
{'id':'BR_S1E08_DOC_TG09','episode':'S1E08','after':'BR_S1E08_A01_SC04','channel':'tethergrid','setting':'Tethergrid emergency launch advisory — severe but technically grounded corridor graphics.','summary':'A heavy unlicensed launch path crosses a restricted orbital corridor while uncertainty cones widen around storm-obscured tracking and ground exclusion zones.','narration':'A heavy launch vehicle does not become safe because its purpose is sympathetic. Shared sky requires verified trajectories, accountable operators and reliable exclusion zones.'},
{'id':'BR_S1E08_DOC_DL09','episode':'S1E08','after':'BR_S1E08_A01_SC05','channel':'dryline','setting':'The Dryline Report — month-long comparison of Public Sky draw, reserve and trip data against former Tetherwell allocations.','summary':'Community draw bars remain below their prior contracted Tetherwell volumes while reserve bands stay visible. The launch-safety warning remains on screen beside the separate water-allocation record.','narration':'The launch dispute is real. It is also separate from the water dispute. Public Sky communities used less water this month than their old contracts permitted.'}
]; dump(p,d)
p=S/'dialogue-voice-rewrites.json'; q=load(p); dump(p,{k:v for k,v in q.items() if not re.match(r'BR_S1E0[4-8]_',k)})
p=S/'dialogue-adaptation-notes.md'; x=p.read_text(); x=x.replace('- Episodes 6–8 remain outline-only until authored scene material exists; do not fabricate full episodes from those outlines.','- Episodes 6–8 are now fully source-authored production sequences. Preserve their authored dialogue and late-season causal structure rather than regenerating them from the retired outline payloads.'); p.write_text(x)
p=R/'tools/validate_backyard_rockets.py'; x=p.read_text(); x=re.sub(r'expected_authored = \{.*?\n\}', 'expected_authored = {\n    "S1E01": 20,\n    "S1E02": 30,\n    "S1E03": 19,\n    "S1E04": 18,\n    "S1E05": 21,\n    "S1E06": 19,\n    "S1E07": 19,\n    "S1E08": 22,\n}',x,count=1,flags=re.S); x=re.sub(r'for ep in \("S1E06", "S1E07", "S1E08"\):\n\s+if counts\[ep\] < 1:\n\s+raise SystemExit\(f"\{ep\}: outline-only episode has no production adaptation beats"\)\n','',x); p.write_text(x)
p=R/'tools/audit_backyard_rockets_continuity.py'; x=p.read_text(); x=x.replace('"Tamz":"@brk.Tamz","Tetherwell Narrator"','"Tamz":"@brk.Tamz","Tamsin":"@brk.Tamsin","Tetherwell Narrator"'); p.write_text(x)
for p in list((S/'raw').glob('e04*.json'))+list((S/'raw').glob('scenes_e04*.json'))+list((S/'raw').glob('e05*.json'))+list((S/'raw').glob('scenes_e05*.json')): p.unlink(missing_ok=True)
for n in range(4,9):
 for p in (S/'encoded').glob(f'scenes_e{n:02d}*.json.gzb64'):
  if p.name not in {'scenes_e04_trip_point.json.gzb64','scenes_e05_reserve_margin.json.gzb64','scenes_e06_ground_loop.json.gzb64','scenes_e07_ablative_armor.json.gzb64','scenes_e08_sky_piercer.json.gzb64'}: p.unlink(missing_ok=True)
print('Late-season metadata activated')
